### ISSUE TITLE
Extract Targets, Verify & Reset components from App

### ISSUE THREAD

**Issue by KrisLamote** [KrisLamote/dyscalc#13]
Preferably to be picked up by a react beginner

**Comment by PragunSaini** [comment]
I am willing to work on this, but can you explain a bit in detail what to do?

**Comment by KrisLamote** [comment]
👍 Sure thing !

Taking "Verify" as an example:

Below jsx portion from App.js needs to be extracted in to a Verify.js component:

```jsx
<div id="verify" className="col-md-auto">
    <button className="btn btn-sm btn-outline-primary">
       VERIFY
    </button>
</div>
```

You could take Cell or row as an example. For the time being there is no interaction, so you don't need props nor PropTypes. Basically you just return that jsx bit.

In App.js you can include you new component and replace the above jsx with this:

```jsx
<Verify />
```

Good luck!

Give me a shout if you have any question

**Comment by PragunSaini** [comment]
Ohk got it

**Comment by KrisLamote** [comment]
👌🏼
