### ISSUE TITLE
Toggle target

### ISSUE THREAD

**Issue by KrisLamote** [KrisLamote/dyscalc#15]
Using the useState hook, update Targets to select a target.

- Be sure to check App.scss for the right classes
- use classnames package to handle ````const classes = classNames(/* conditions */);````
- initially no target cell is selected
- clicking a cell makes that the selected cell
- clicking a selected cell, unselects the cell

**Comment by KrisLamote** [comment]
If you pick this - please start on it immediately
If it's not picked I'll do this over my lunch break (yes - today)

**Comment by trojano31** [comment]
I'll take it ;)

**Comment by KrisLamote** [comment]
👍 good luck!

**Comment by KrisLamote** [comment]
@trojano31 Patrick - if you want, got a new one - very similer, building on to what you just contributes.

**Comment by trojano31** [comment]
I'll check it ;)
