### ISSUE TITLE
Reorganise for better responsive qualities

### ISSUE THREAD

**Issue by KrisLamote** [KrisLamote/dyscalc#16]
Currently the layout breaks on smaller devices.. basic suggestion as follows

- 1st row: Header
- 2nd row: Board & Targets each in their own col
- 3rd row: menu buttons Verify & Reset, right aligned so they Reset aligns with the targets while on a reasonable width device?

**Comment by RyanMan56** [comment]
@KrisLamote I'm happy to work on this if it hasn't been assigned to anybody else yet

**Comment by KrisLamote** [comment]
Sure Ryan - have fun :)

**Comment by KrisLamote** [comment]
Oops hold on a sec, seems there another PR related to this

**Comment by KrisLamote** [comment]
Ok sorry about that, make sure you pull the latest version

**Comment by RyanMan56** [comment]
@KrisLamote after those latest changes it's looking pretty responsive to me, especially in terms of your suggestions. Are there any other improvements you had in mind? :)

**Comment by KrisLamote** [comment]
I know, I'd better refuse PR's by contributors who didn't get the specific issue assigned :(

However with the current version it's difficult to get to the reset button on small screens (it falls all the way to the bottom) - maybe it's still better to have the target buttons and the verify and reset buttons in the same column.

I would prefer a different layout / position for the verify & reset button (underneath the board) for srceens size >= 692px but that's entirely optional. Heck I am clearly not a designer :)

**Comment by AhsanAyaz** [comment]
@KrisLamote I'm on this 🙂
