### ISSUE TITLE
Toggle Cell

### ISSUE THREAD

**Issue by KrisLamote** [KrisLamote/dyscalc#18]
When a target is selected, the board cells can be toggle on/off depending on the selected target, giving them the corresponding target colour.

See 3c693719226d1049ab8e2e88b5a4a57e5f29a97f

- Pull up activeTarget & setActiveTarget to App
- pass them to Targets with appriate PropTypes
- pass activeTarget through to the Cells
- use useState to toggle a Cell
- use classnames to set/unset a `target-${idx}` class (double check with App.scss)

**Comment by KrisLamote** [comment]
If you pick this - please start on it immediately
If it's not picked I'll do this over my lunch break (yes - today)

**Comment by trojano31** [comment]
I'll take it
