### ISSUE TITLE
Reset interaction

### ISSUE THREAD

**Issue by KrisLamote** [KrisLamote/dyscalc#19]
When Reset is clicked the board & targets should be reinitialised.

- convert ```const targets = pickSome(/* ... */);``` with useState
- pass the setTargets function to Reset
- update Reset with an onClick

depending on the status of #18 you may have to reset the target as well, probably best to wrap both at the level of App

**Comment by DmitriiKholodov** [comment]
@KrisLamote What time of your lunch? I would take this task :)

**Comment by KrisLamote** [comment]
there you go Dmitrii

Good point - lunch time for me would be 12-13 CET (I'm in Brussels)
But no worries, I can find other things to look at :)

**Comment by KrisLamote** [comment]
Contribution guidelines have changed (README.md) - just standard stuff, fork 1st

**Comment by DmitriiKholodov** [comment]
@KrisLamote Hey, that's great! Actually it's my first experience with pr from forked branch.

**Comment by KrisLamote** [comment]
b1b6f1704d922ef91a6a8f0ec4d16b4e377ebe68
