### ISSUE TITLE
Apply Transition when Resetting

### ISSUE THREAD

**Issue by KrisLamote** [KrisLamote/dyscalc#26]
Currently there is only a visual transition when the board is initially rendered. When you do a reset, the fact that the board is updated isn't very clear (well if you haven't selected anything)

**Comment by thedeany** [comment]
I'd like to take this!

**Comment by KrisLamote** [comment]
By all means - thanks for showing interest

**Comment by thedeany** [comment]
So, I took a long look at this issue, and I'm not seeing a way to retrigger the `CSSAnimation` on reset. To get `CSSAnimation` to be re-rendered, a `key` prop must be assigned. This works as expected, but it is re-rendered when you click virtually anything.

Any ideas?

**Comment by KrisLamote** [comment]
Normally a useEffect 'watching' this specific property should do the trick.
If you want you can push your branch and I can have a look, or even do a PR which I can review and comment on

**Comment by thedeany** [comment]
Ahh, I’m new to Hooks, so I hadn’t thought about `useEffect`. I’ll give that a try.

**Comment by thedeany** [comment]
Well, I feel dumb. I guess I already was trying to use the existing `useEffect` in `Cell.js` and couldn't figure out why it wasn't working. After the `CSSTransition` component mounts, the CSS classes it uses thereafter are different than the classes it uses on its initial appearance. After adding these classes to the `.scss` file so the `transition` could occur, things are working!
