### ISSUE TITLE
Options button, toggles visibility of an options container 

### ISSUE THREAD

**Issue by KrisLamote** [KrisLamote/dyscalc#29]
While the options are visible the Board, Targets, Verify & Reset are invisible. Maybe these can be wrapped in Game. The current options will be displayed in the options container and at the a 'back to game' button:

- up to 10 / up to 20
- sum / subtraction / both
- 3 / 4 / 5 targets

Probably a 3-state type of button could work. For the time being these could be disabled.

**Comment by mazma1** [comment]
Hi @KrisLamote, I'll love to help with this.
Can you help me clarify what you mean by "For the time being these could be disabled"?

**Comment by KrisLamote** [comment]
Thanks for showing interest @mazma1 
What I mean by "for the time being" is that I prefer to keep issues small and focused. It also gives me (and others) the possibility to get new insights into where this could/should be heading. So priority is to get that options toggle feature in - there will definately be a new issue out to get every option updatable :)

**Comment by mazma1** [comment]
Oh, that makes a lot of sense now. I'll jump on it right away.

**Comment by KrisLamote** [comment]
c5ee17d3e0d696ef09dfd16c095e5c00bc98c4f5

Thanks @mazma1 !
