### ISSUE TITLE
keep 'track' of board completeness show some success message

### ISSUE THREAD

**Issue by KrisLamote** [KrisLamote/dyscalc#30]
When all cells are assigned correctly, show some kind of success message, with an option to start over (i.e. reset)

**Comment by AhsanAyaz** [comment]
On it

**Comment by KrisLamote** [comment]
Wow a motivated contributor 👍

**Comment by AhsanAyaz** [comment]
Haha. Always!

**Comment by KrisLamote** [comment]
Hey @AhsanAyaz - first of this is simply me reaching out for collaboration, no pressure in the slightest way.

I am aware this feature may have some impact through out the entire code base. If you want to share/discuss some design options - feel free adding them here. If need be we can create an 'idea/question' issue to channel some of the discussion.

Cheers - Kris

**Comment by AhsanAyaz** [comment]
Hey @KrisLamote .
I got a bit busy with the usual work stuff.
And yes, this impacts probably the entire code base as props are being passed from top to bottom in terms of hierarchy.
Are we considering using Redux by any chance? Or would you just want to keep it React components only?

**Comment by KrisLamote** [comment]
Yes we're getting in the classic situation with all state & logic at the root level & propdrilling in the component hierarchy. I think the context API and/or useReducer could be a good fit for this size a project - what do you think?

**Comment by KrisLamote** [comment]
see #43

**Comment by AmanAgarwal041** [comment]
@KrisLamote @AhsanAyaz  I have managed corrects left to win the game in a different component and wrapped the other as render props and passed on the functions for attempting correct and wrong. I have issued a [pull request](https://github.com/KrisLamote/dyscalc/pull/47) have a look at it.

**Comment by KrisLamote** [comment]
@AhsanAyaz did you start on a feature branch? Closing this for now ref 8892359d46bfcd59c8c69138c55fd3955fe281af
