### ISSUE TITLE
travis configuration

### ISSUE THREAD

**Issue by KrisLamote** [KrisLamote/dyscalc#34]
Add a travis configuration as appropriate to a simple react app. This should at least run the tests. Any other suggestions are -as always- welcome

**Comment by bigfpanda** [comment]
I'll work on this

**Comment by bigfpanda** [comment]
Let me know if I have to add travis badge as well in README file

**Comment by KrisLamote** [comment]
Thanks @bigfpanda, first build is a success :+1:

**Comment by bigfpanda** [comment]
You are welcome, I feel happy with it
