### ISSUE TITLE
Helper functions for initializing the game board

### ISSUE THREAD

**Issue by KrisLamote** [KrisLamote/dyscalc#4]
Add a helper.js which can:
- [x] generate a range based on start & stop params ( range(2, 7) => [2, 3, 4, 5, 6, 7] )
- [x] pickOne(arr): returns a random element from the provided array
- [ ] pick(arr, amount): return an array of 'amount' elements from arr (no duplictes)

**Comment by DmitriiKholodov** [comment]
I can get the first task to start, please assign me

**Comment by KrisLamote** [comment]
OK I'll slightly rearrange this, so this can more gracefully be collaborated on in conjunction with issue#3

**Comment by DmitriiKholodov** [comment]
What an issue #3, i can't find it

**Comment by KrisLamote** [comment]
My bad I was referring to issue 5

**Comment by KrisLamote** [comment]
75ce9c11a182fef721bebc384076bd231452766c

**Comment by DmitriiKholodov** [comment]
@KrisLamote Could you explain to me how you will exclude duplicates? Thanks!

**Comment by KrisLamote** [comment]
Because Array.splice modifies the array (in this case the variable arr) and returns the deleted elements (const elements). So the clue is in line 22 of helpers.js

**Comment by DmitriiKholodov** [comment]
Oh, i see, big thanks

ср, 2 окт. 2019 г., 23:40 KrisLamote <notifications@github.com>:

**Comment by KrisLamote** [comment]
In fact it would would be a good idea to add tests for these things e.g. with jest.
I've updated the function for better readability (see 9abf90db482b8f5133d161bde6a09ea723fe2358)
