### ISSUE TITLE
Intl next steps

### ISSUE THREAD

**Issue by KrisLamote** [KrisLamote/dyscalc#40]
- [x] use json files for translations
- [ ] move provider outside App

### Discussion topics

This is a follow on for #6 - for the time being simply gathering some idea's opinions

- overlooked the js translations I prefer them to be json files
- I actually liked the idea of having the Provider outside App as it simply moves a concern from a file that already has a few different responsibilities

**Comment by caleniuc** [comment]
1. 
- Ok, this can be easily modified. Did them in js and not json as I'm used to leave comments. But this not being a large app, json would be fine for translation files.

- Also a benefit for json files would be that it's easier to load translations from a remote server/local path from same server, so anyone could translate it on the fly, without the app needing to be redeployed.

2.  I also liked it, but changed it in order for the test to pass. Maybe a Root component can be created that wraps App, or simply keep the intl logic in index.js and enhance the tests with some helper functions that gives the intl prop to the tested components

**Comment by KrisLamote** [comment]
good point about comments, though it looks like we agree on json for dyscalc

**Comment by KrisLamote** [comment]
I think moving up the provider to the index.js - may 'simply' imply the same changes to be made in App.test.js - I might have a look at that later today
