### ISSUE TITLE
reorganize cells state

### ISSUE THREAD

**Issue by KrisLamote** [KrisLamote/dyscalc#43]
Currently the state of each cell is managed in the Cell component:

```javascript
const [target, setTarget] = useState(pickOne(targets));
const [term, setTerm] = useState(pickOne(range(1, target - 1)));
const [selected, setSelected] = useState(empty);
// ...
 useEffect(() => {
        setTarget(pickOne(targets));
        setTerm(pickOne(range(1, target - 1)));
        setSelected({ idx: null, value: null });
        // ...
    }, [targets, target]);
```

It's probably better to have the entire board as an array in App or Board and have the (chosen) target and a (derived) term handled there. This will be mandatory for more easily determine whether the game is done or not (see #30 . Finally this will be a good way to avoid having to pass the options all the way down as well (see #29)

**Comment by AmanAgarwal041** [comment]
I have maintained total number of correct attempts left on the root level. Passed function to the innermost cells to call on success and failure.

**Comment by AmanAgarwal041** [comment]
@KrisLamote Can we close this issue ?

**Comment by KrisLamote** [comment]
I was thinking to take this a little further with per cell the target and term chosen at the app level. More or less based on this tic-tac-toe example by Kent C Dodds:
https://github.com/kentcdodds/learn-react-hooks/blob/master/src/exercises-final/04.js

But as a matter of fact you are right - this can be closed. If we want/need to take it further, this can be reopened.
