### ISSUE TITLE
options: toggle 10 | 20

### ISSUE THREAD

**Issue by KrisLamote** [KrisLamote/dyscalc#45]
Enable the **Upto 10 | 20** toggle button

- keep the state in App
- use it to generate the targets

Bonus useReducer so we can handle the 3 different options (upto, targets & operation)

**Comment by AmanAgarwal041** [comment]
I am working on this.

**Comment by svnnynior** [comment]
Hi @KrisLamote, Could I take this one ?

**Comment by KrisLamote** [comment]
Heads-up, could take a while before I get to do the PR review .. sorry

**Comment by svnnynior** [comment]
It's okay, take your time  😉

**Comment by KrisLamote** [comment]
185dc445d392304a9ab8c74123a3b6cfff9d6584
