### ISSUE TITLE
Extract Board, Row & Cell components out of App

### ISSUE THREAD

**Issue by KrisLamote** [KrisLamote/dyscalc#5]
- [x] Cell
- [x] Row (containing Cells)
- [x] Board (containing Rows)

**Comment by ijunaidali** [comment]
hi I wanna pick this up

**Comment by DmitriiKholodov** [comment]
Oh , i'm already done it, but i forgot to assign((

**Comment by KrisLamote** [comment]
Hey Dmitri - nice, however Junaid was using this to get up to speed. He'll be done shortly. If you want I can get you something else to work on? And if you want a code review of what you did so far, feel free to push it as a feature branch.

**Comment by DmitriiKholodov** [comment]
I cant push my feature-branch, because i have permission denied. What am I doing wrong?
![image](https://user-images.githubusercontent.com/28441549/66027722-2c74e900-e504-11e9-8687-6e852f7ec416.png)

**Comment by KrisLamote** [comment]
I'm guessing you are on a local branch 'add-board-row-cell-components' right now?
Can you try `git push origin add-board-row-components` ?
If not, what is `git branch` saying?

**Comment by DmitriiKholodov** [comment]
the name is 'add-board-row-components', i tried to push without -u, but still dosent work

**Comment by KrisLamote** [comment]
any change after adding you as a collaborator - yeah sorry about this, I am trying what's wrong ...

**Comment by KrisLamote** [comment]
c87f457166c04cc2c1ccb3f2a223e077ff27c606
