### ISSUE TITLE
automatic formatting or format checking (prettier | travis) 

### ISSUE THREAD

**Issue by KrisLamote** [KrisLamote/dyscalc#52]
Any suggestions for improving the js|jsx|json formatting in this project. I continuously keep auto-formatting files as they come in through various PRs. I have slightly different settings between 2 work stations, so this even happens in my own contributions.

Any suggestions are welcome.

**Comment by IsraelSampaio** [comment]
if for code formatting, one question, Have you used eslint?
If not, I can implement for you @KrisLamote . :)

**Comment by KrisLamote** [comment]
Yes (in bigger projects) I see the nees for adding it to dyscalc as well

**Comment by IsraelSampaio** [comment]
ok, i will add.
