### ISSUE TITLE
Bug Verify ON/OFF (translations)

### ISSUE THREAD

**Issue by KrisLamote** [KrisLamote/dyscalc#59]
The ON/OFF trailer of the button was done before translations were added. Currently it just adds ON/OFF behind the 'VERIFY' translation.

Changing this to have the menu.verify.on & menu.verify.off labels translated should fix this

**Comment by manikkalai-kannan** [comment]
will take that up

**Comment by KrisLamote** [comment]
Thanks - Have fun!

**Comment by KrisLamote** [comment]
hm yeah - sorry had the wrong reference
