### ISSUE TITLE
Add intl basics

### ISSUE THREAD

**Issue by KrisLamote** [KrisLamote/dyscalc#6]
- [ ] add **react-intl** package
- [ ] add FormattedMessages for the verify & reset buttons
- [ ] add translations for your native language

(will create a separate issue for a language switch)

**Comment by KrisLamote** [comment]
I only have experience with react-intl v2 (current is v3.2.1)

**Comment by ijunaidali** [comment]
i will pick it

**Comment by KrisLamote** [comment]
make sure you use the latest version react-intl, good luck

**Comment by KrisLamote** [comment]
This issue is up for grabs again - any help is appreciated

**Comment by caleniuc** [comment]
I will try this
